#!/usr/bin/env bash

##
# @brief Generate Doxygen documentation for project sources.
# @details Uses system-installed doxygen to scan `src/` and emit HTML, LaTeX/PDF, and Markdown outputs in `doxygen/`.
# @param[in] None {void} Script does not accept positional arguments.
# @return {int} Exit status code. `0` on success; non-zero on validation or generation failure.
##
main() {
  set -euo pipefail

  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  cd "${script_dir}"

  require_command "doxygen"
  require_command "pdflatex"
  require_command "makeindex"
  require_command "pandoc"

  prepare_output_directories

  local have_dot="NO"
  if command -v dot >/dev/null 2>&1; then
    have_dot="YES"
  fi

  local doxyfile
  doxyfile="$(mktemp /tmp/doxygen.XXXXXX.conf)"

  write_doxyfile "${doxyfile}" "${have_dot}" "${script_dir}"
  doxygen "${doxyfile}"
  build_pdf_documentation
  build_markdown_documentation
  rm -f "${doxyfile}"

  printf '%s\n' "Generated documentation:"
  printf '%s\n' "  - HTML: doxygen/html"
  printf '%s\n' "  - PDF: doxygen/pdf/refman.pdf"
  printf '%s\n' "  - Markdown: doxygen/markdown"
}

##
# @brief Ensure a required command exists in PATH.
# @details Resolves command availability with `command -v`; exits with explicit error when unavailable.
# @param[in] cmd_name {string} Executable name to validate in PATH.
# @return {int} Exit status code. `0` when command exists; exits non-zero otherwise.
##
require_command() {
  local cmd_name="${1}"
  if ! command -v "${cmd_name}" >/dev/null 2>&1; then
    printf 'ERROR: required command not found: %s\n' "${cmd_name}" >&2
    exit 1
  fi
}

##
# @brief Recreate output directories for deterministic documentation generation.
# @details Deletes prior format-specific output folders and creates empty `doxygen/html`, `doxygen/pdf`, and `doxygen/markdown`.
# @param[in] None {void} Function reads no input.
# @return {int} Exit status code from filesystem operations.
##
prepare_output_directories() {
  rm -rf doxygen/html doxygen/pdf doxygen/markdown
  mkdir -p doxygen/html doxygen/pdf doxygen/markdown
}

##
# @brief Compile Doxygen LaTeX output into PDF.
# @details Executes deterministic LaTeX pipeline (`pdflatex`, `makeindex`, `pdflatex`, `pdflatex`) in `doxygen/pdf` and validates `refman.pdf` existence.
# @param[in] None {void} Function reads no input.
# @return {int} Exit status code. Non-zero when PDF artifact is missing after compilation.
##
build_pdf_documentation() {
  (
    cd doxygen/pdf
    pdflatex -interaction=nonstopmode refman.tex >/dev/null || true
    makeindex refman.idx >/dev/null
    pdflatex -interaction=nonstopmode refman.tex >/dev/null || true
    pdflatex -interaction=nonstopmode refman.tex >/dev/null || true
  )

  if [[ ! -f doxygen/pdf/refman.pdf ]]; then
    printf '%s\n' "ERROR: expected PDF artifact not generated: doxygen/pdf/refman.pdf" >&2
    exit 1
  fi
}

##
# @brief Generate Markdown artifacts from Doxygen HTML output.
# @details Converts each HTML page generated by Doxygen into GitHub-flavored Markdown using `pandoc`, preserving relative directory structure under `doxygen/markdown`.
# @param[in] None {void} Function reads no input.
# @return {int} Exit status code from conversion loop.
##
build_markdown_documentation() {
  local html_file
  while IFS= read -r html_file; do
    local relative_path
    relative_path="${html_file#doxygen/html/}"
    local markdown_path
    markdown_path="doxygen/markdown/${relative_path%.html}.md"
    mkdir -p "$(dirname "${markdown_path}")"
    pandoc --from=html --to=gfm "${html_file}" -o "${markdown_path}"
  done < <(find doxygen/html -type f -name '*.html')
}

##
# @brief Write Doxygen configuration file.
# @details Emits best-practice options for full source extraction, recursive scan, and multi-format output generation from `src/`.
# @param[in] target_file {string} Absolute path to generated temporary Doxygen configuration file.
# @param[in] have_dot {string} Graphviz availability flag (`YES` or `NO`) used for `HAVE_DOT`.
# @param[in] project_root {string} Absolute path to repository root used for `STRIP_FROM_PATH`.
# @return {int} Exit status code from file write operation.
##
write_doxyfile() {
  local target_file="${1}"
  local have_dot="${2}"
  local project_root="${3}"
  cat > "${target_file}" <<EOF
PROJECT_NAME           = "Git-Alias CLI"
PROJECT_BRIEF          = "Generated API documentation"
OUTPUT_DIRECTORY       = .
INPUT                  = src
FILE_PATTERNS          = *.py
RECURSIVE              = YES
EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = YES
EXTRACT_STATIC         = YES
EXTRACT_LOCAL_CLASSES  = YES
EXTRACT_LOCAL_METHODS  = YES
JAVADOC_AUTOBRIEF      = YES
MULTILINE_CPP_IS_BRIEF = YES
INHERIT_DOCS           = YES
QUIET                  = YES
WARN_IF_UNDOCUMENTED   = NO
WARN_IF_DOC_ERROR      = YES
WARN_NO_PARAMDOC       = NO
SOURCE_BROWSER         = YES
INLINE_SOURCES         = NO
REFERENCED_BY_RELATION = YES
REFERENCES_RELATION    = YES
ALPHABETICAL_INDEX     = YES
FULL_PATH_NAMES        = NO
STRIP_FROM_PATH        = ${project_root}
HAVE_DOT               = ${have_dot}
CALL_GRAPH             = YES
CALLER_GRAPH           = YES
DOT_IMAGE_FORMAT       = svg
DOT_MULTI_TARGETS      = YES

GENERATE_HTML          = YES
HTML_OUTPUT            = doxygen/html
GENERATE_TREEVIEW      = YES

GENERATE_LATEX         = YES
LATEX_OUTPUT           = doxygen/pdf
USE_PDFLATEX           = YES
PDF_HYPERLINKS         = YES
LATEX_BATCHMODE        = YES
TOC_INCLUDE_HEADINGS   = 3
EOF
}

main "$@"
